### ISSUE TITLE
NS_DEPLOY_FAILED when SP still INSTANTIATING

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/tng-vnv-lcm#34]
Hello!

Currently, the VnV deploy a NS using the SP triggered by a test. In the process, the VnV polls to SP each second if the NS was deployed, after 1 minuted VnV considered the test failed because NS_DEPLOY_FAILED.

The issue is that the SP is still working on it so for y1 we have some options:
* Increase the waiting time to 600 seconds
* Implement a callback in the GK of the SP to inform the result of the instantiation
* Include in the descriptor the maximum time to wait for the instantiation

@jbonnet @midlakelands @allemaos @mrduguo thoughts?

**Comment by jbonnet** [comment]
Thanks, @felipevicens for raising the issue.
Polling every second is **overkill**, taking into account that a services takes 3 to 4 mins to be instantiated. I'd say that polling every **30 secs** would be enough. We need to implement a callback mechanism (which is already there, but needs to be tested: one of the parameters of the instantiation request can already be a callback URL, but sunce there were no clients for it, it is not yet being called upon service instantiation).

Only one minute to time-out is also too short (see above).

**Comment by mrduguo** [comment]
implemented with polling every 30 seconds and wait for 10 minutes before give up
