### ISSUE TITLE
Endpoint to trigger a test [ref @felipevicens sonata-nfv/tng-vnv-tee: #8]

### ISSUE THREAD

**Issue by andreoug** [sonata-nfv/tng-vnv-lcm#37]
In sonata-nfv/tng-vnv-tee, @felipevicens said "I need an endpoint to trigger a specific test". 
This endpoint that will be triggered for a specific test will be available through tng-vnv-lcm comp. 

ref: @felipevicens  sonata-nfv/tng-vnv-tee: [#8](https://github.com/sonata-nfv/tng-vnv-tee/issues/8)

**Comment by jbonnet** [comment]
@allemaos tell me the API ASAP, I need to make it public in the Gatekeeper

**Comment by andreoug** [comment]
Issue resolved with endpoints:

POST /api/v1/schedulers/services with body: { "service_uuid": "<service_uuid>"}
POST /api/v1/schedulers/tests with body: { "test_uuid": "<test_uuid>"}

Ty
